version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bin/rails s -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      TZ: Asia/Tokyo

volumes:
  db-data: